### ISSUE TITLE
PyTorch upgrade to version 1.5

### ISSUE THREAD

**Issue by sebbarb** [VIEW2020/Varianz2012#5]
PyTorch upgrade to version 1.5 is needed to fix issues with non-zero gradient on padding_idx for nn.embedding (bug https://github.com/pytorch/pytorch/issues/26302 )

**Comment by VIEW2020** [comment]
Torch 1.5.0 successfully installed

**Comment by sebbarb** [comment]
Hi, it still shows me 1.3.1 as the installed version.

**Comment by VIEW2020** [comment]
I have copied the site-packages directory to the D: drive. You could either copy the relevant folders into one of your your environment's `sys.path` or set a new library path pointing to D:/site-packages/

Reference: https://www.devdungeon.com/content/python-import-syspath-and-pythonpath-tutorial#toc-5

**Comment by sebbarb** [comment]
Awesome, working fine now!
