### ISSUE TITLE
installation of statsmodels python package

### ISSUE THREAD

**Issue by sebbarb** [VIEW2020/Varianz2012#6]
The statsmodels package for python is needed to determine confidence intervals around the computed hazard ratios.

**Comment by VIEW2020** [comment]
statsmodels 0.10.1 successfully installed

**Comment by sebbarb** [comment]
Hi, I'm still not able to import it (ModuleNotFoundError)

**Comment by VIEW2020** [comment]
I have copied the site-packages directory to the D: drive. You could either copy the relevant folders into one of your your environment's `sys.path` or set a new library path pointing to D:/site-packages/

Reference: https://www.devdungeon.com/content/python-import-syspath-and-pythonpath-tutorial#toc-5

**Comment by sebbarb** [comment]
Awesome, working fine now!
